---
title: "EC 421"
subtitle: "Final Topics from \"New\" Lectures"
#author: "Edward Rubin"
date: "Spring 2019<br><br>.smallest[**Note.sub[1]:** The final exam will focus on the following topics. I will also assume an understanding of the material from the midterm.<br><br>**Note.sub[2]:** As with the midterm, you do not need to memorize proofs. Understand the steps/reasoning. Intuition is paramount. I might ask how you get from one step to the next. I won't ask you to write down a full proof.]"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: clear

## Slide Set 7: Time Series

- Notation
- Assumptions
- Static models
- Dynamic models
  - With lagged explanatory variables
  - Autoregressive, distributed lag (ADL) models
  - ADL(p,q)
  - Long-run vs. short-run effects
- Contemporaenous exogeneity

## Slide Set 8: Autocorrelation

- Definition of autocorrelation
- Negative and positive autocorrelation
- Equation/formula for AR(p) processes
- OLS implications for static models and dynamic models with lagged explanatory variables
- OLS implications/bias for dynamic models with lagged dependent variables
- Breusch-Godfrey test
  - Hypotheses
  - Interpretation of results
  - Conclusion
- Misspecification
- FGLS: General idea

## Slide Set 9: Non-Stationary Time Series

- Definition/requirements of nonstationarity
  - Mean
  - Variance
  - Covariance
- Random walks
- Spurious correlations
- Differencing

---
class: clear

## Slide Set 10: Causality

- Prediction vs. causal inference/estimation
- Correlation vs. causation
- Experiments/RCTs
- The "ideal experiment" (ideal dataset)
- Treatment effects:
  - Individual effects
  - Average treatment effects
  - Constant treatment effects
- Selection bias

## Slide Set 11: Instrumental Variables

- Exogeneity and endogeneity
- Requirements for a valid instrument
  - Relevant
  - Exogenous
- Probability limit
- Venn diagrams
- First stage and reduced form
- Two-stage least squares
  - Motivation
  - First stage
  - Second stage
- Interpretation

---
exclude: true

```{R, generate pdfs, include = F, eval = T}
system("decktape remark final_topics.html final_topics.pdf --chrome-arg=--allow-file-access-from-files")
```
