---
title: "Problem Set 3 Solutions"
subtitle: "Time Series and Autocorrelation"
author: "**EC 421:** Introduction to Econometrics"
date: "<br>Due *before* midnight (11:59pm) on Wednesday, 29 May 2019"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      ratio: '8.5:11'
      # ratio: '8.8:11.4'
      # ratio: '8.4:10.87'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: clear

.mono[DUE] Your solutions to this problem set are due *before* midnight on Wednesday, 29 May 2019. Your files must be uploaded to [Canvas](https://canvas.uoregon.edu/).

.mono.b[IMPORTANT] Your submission must include (1) **your responses/answers to the question in a PDF, Word, or similar file** and (2) the .mono[R] script you used to generate your answers. **The .mono[R] script is just for your code. To receive credit, your answers/figures/*etc.* must be in the PDF/Word document.** Each student must turn in her/his own answers.

.mono[OBJECTIVE] This problem set has three purposes: (1) reinforce the econometrics topics we reviewed in class; (2) build your .mono[R] toolset; (3) start building your intuition about causality and time series within econometrics.

## Problem 1: Time Series

Imagine that we are interested in estimating the effect of monthly oil prices on monthly natural gas prices. The dataset `ps03_data.csv` contains these prices—the monthly average oil price (the price in dollars per barrel of *Brent Crude oil*, as measured by the [US EIA](https://www.eia.gov/dnav/pet/hist/RBRTED.htm)) and the monthly average price of natural gas (dollars per million BTUs for natural gas at the *Henry Hub*, recorded by the [US EIA](https://www.eia.gov/dnav/ng/hist/rngwhhdm.htm)).

The table on the last page describes the variables in this dataset.

**1a.** First, we consider the possibility that $P_t^\text{Oil}$ (the price of oil in month $t$) only depends upon a constant $\beta_0$, $P_t^\text{Gas}$ (the price of natural gas in month $t$), and a random disturbance $u_t$.

$$
\begin{align}
  P_t^\text{Oil} = \beta_0 + \beta_1 P_t^\text{Gas} + u_t \tag{1a}
\end{align}
$$

If model $(1\text{a})$ is the true model, should we expect OLS to be consistent for $\beta_1$? **Explain.**

.pink[

.b[Answer] The model in (1a) is a *static time-series* model—there are no lags of the explanatory or dependent variables. OLS is consistent for estimating the $\beta_j$ in static time-series models. (As long as there are no omitted variables, which may be assumed by the term "true model".)

*Note:* We're ignoring nonstationarity.

]

---
class: clear

**1b.** Read `ps03_data.csv` and summarize them.

How many observations do you have? Which months/years do they cover? (*Hint:* use `nrow()`, `head()`, and `tail()`).

Now estimate model $(1\text{a})$ with OLS. Interpret your estimate for $\beta_1$ and comment on its statistical significance.

.pink[

.b[Answer]

```{R, key 1b, message = F, include = T}
# Load packages
library(pacman)
p_load(tidyverse, broom, here)
# Load data
price_df <- read_csv("ps03_data.csv")
# Number of observations
nrow(price_df)
# Summary of data
summary(price_df)
# Estimate model 1a with OLS
ols_1a <- lm(price_oil ~ price_gas, data = price_df)
# Results
tidy(ols_1a)
```

We have `r nrow(price_df)` observations, staring in January of 1997 and running until April of 2019.

Our estimate for $\beta_1$ in equation (1a) is approximately `r round(ols_1a$coefficients[2], 3)`, and it is statistically significant at the 5-percent level. *Interpretation:* Holding all else constant, if the price of natural gas increases by 1 dollar, we expect the price of oil to increase by `r round(ols_1a$coefficients[2], 3)`.

]

---
class: clear

**1c.** In (1b), you should have found that the coefficient on $P_t^\text{Gas}$ is statistically significant. Does this finding also mean that the price of natural gas explains a lot of the variation in the price of oil?

*Hint:* What is the R.super[2]? (In .mono[R], you can find R.super[2] using `summary()` applied to a model you estimated with `lm()`.)

.pink[

.b[Answer]

```{R, key 1c, message = F, include = F}
summary(ols_1a)
```

Our model in (1a) has an R.super[2] of approximately `r round(summary(ols_1a)$r.squared, 4)`, which suggests that the price of oil explains a fairly small amount of the variation in the price of natural gas, despite the fact that the correlation between the two variables is statistically significant. Statistical significance does not tell us whether the variable explains a substantial amount of variation.

]

**1d.** The model that we estimated in (1a) is a static model—meaning it does not allow previous periods' prices to affect the current price of oil. Suppose we think believe that the previous two months' natural gas prices also affect the price of oil, *i.e.*,

$$
\begin{align}
  P_t^\text{Oil} = \beta_0 + \beta_1 P_t^\text{Gas} + \beta_2 P_{t-1}^\text{Gas} + \beta_3 P_{t-2}^\text{Gas} + u_t \tag{1d}
\end{align}
$$

Estimate this model and compare your new estimate for $\beta_1$ to your previous estimate (from model 1a).

*Hint:* Use the function `lag(x, n)` from the `dplyr` package to take the `n`.sup[th] lag of variable `x`.

.pink[

.b[Answer]

```{R, key 1d, include = T}
# Estimate model 1d with OLS
ols_1d <- lm(
  price_oil ~ price_gas + lag(price_gas, 1) + lag(price_gas, 2),
  data = price_df
)
# Results
tidy(ols_1d)
```
After controlling for the the first and second lags of the price of natural gas, our estimate for $\beta_1$ is now approximately `r round(ols_1d$coefficients[2], 3)` (we previously estimated `r round(ols_1a$coefficients[2], 3)`). The point estimate is smaller and no longer statistically significant.

]

**1e.** Interpret your estimated coefficients for $\beta_2$ and $\beta_3$. Are they statistically significant?

.pink[

.b[Answer] Our estimates for $\beta_2$ and $\beta_3$ are `r round(ols_1d$coefficients[3], 3)` and `r round(ols_1d$coefficients[4], 3)`, respectively.

*Interpretations:* $\hat{\beta}_2$ suggests that when last months' natural gas price increased by one dollar, we expect this month's price for oil to increase by approximately `r round(ols_1d$coefficients[3], 3)` (holding all else constant). Similarly, $\hat{\beta}_3$ suggests that when 2 months' prior price of natural gas increased by one dollar, we expect this month's price of oil to increase by approximately `r round(ols_1d$coefficients[4], 3)` (holding all else constant). However, neither estimate is statistically significant at the 5-percent level.

]

---
class: clear

**1f.** Has the amount of variation that we can explain increased very much? Compare the R.super[2] values for model (1a) and (1d). Also consider the *adjusted* R.super[2].

.pink[
.b[Answer] Nope—we still are not explaining much variation in the price of natural gas. The R.super[2] has .b[increased] very slightly (it's now `r round(summary(ols_1d)$r.squared, 3)`; it was `r round(summary(ols_1a)$r.squared, 3)`). The adjusted R.super[2] has decreased (now `r round(summary(ols_1d)$adj.r.squared, 3)`; was `r round(summary(ols_1a)$adj.r.squared, 3)`).

]

**1g.** Formally test model $(1\text{a})$ vs. model $(1\text{d})$ using an $F$ test.

*Hint:* You can test one model against another model in .mono[R] using the `waldtest()` function from the `lmtest` package. For example,

```{R, hint 1e, eval = F}
# OLS model of y on x and two lags
est_model <- lm(y ~ x + lag(x) + lag(x, 2), data = example_df)
# Jointly test the coefficients on lag(x) and lag(x, 2)
waldtest(est_model, c("lag(x)", "lag(x, 2)"), test = "F")
```
calculates an $F$ test for the coefficients on `lag(x)` and `lag(x, 2)` in the model `est_model`.

**Note:** For some reason, `lag(x, n)` needs to have a space between the comma (`,`) and `n` when you use `waldtest` to test lags.

.pink[

.b[Answer] The Wald test...

```{R, key 1e, include = T}
# Load 'lmtest'
p_load(lmtest)
# F test
waldtest(ols_1d, c("lag(price_gas, 1)", "lag(price_gas, 2)"))
```
The $F$ test comparing the two models fails to reject the null hypothesis at the 5% level with a *p*-value of approximately 0.63. In this test, H.sub[o] is $\beta_2=0$ and $\beta_3=0$ (for model (1d)). Thus, we fail to find statistically significant evidence that the first and second lags of oil natural gas affects the current price of oil (after controlling for the current price of natural gas).

]

**1h.** If model $(1\text{d})$ is the true model, should we expect OLS to be consistent for $\beta_1$? **Explain.**

.pink[
.b[Answer] The model in (1d) only includes lags of the explanatory variable, which means we can expect OLS to be consistent for $\beta_1$,even if $u_t$ is autocorrelated. (Again, we also must assume no omitted variables, which may be assumed by the term "true model".)
]

---
class: clear

**1i.** Suppose we now think that the actual model includes the current price of natural gas *and* the previous month's prices of natural gas and oil, *i.e.*,

$$
\begin{align}
  P_t^\text{Oil} = \beta_0 + \beta_1 P_t^\text{Gas} + \beta_2 P_{t-1}^\text{Gas} + \beta_3 P_{t-1}^\text{Oil} + u_t \tag{1i}
\end{align}
$$

Estimate this model. Interpret the coefficients on $\beta_1$ and $\beta_3$. How has your estimate on $\beta_1$ changed?

.pink[

.b[Answer]

```{R, key 1i, include = T}
# Estimate model 1i with OLS
ols_1i <- lm(
  price_oil ~ price_gas + lag(price_gas, 1) + lag(price_oil, 1),
  data = price_df
)
# Results
tidy(ols_1i)
```

Our estimate for $\beta_1$ is now approximately `r round(ols_1i$coefficients[2], 3)`, which is statistically significant at the 5-percent level. This value is a bit smaller than what we estimated in (1d)—and much smaller than the estimate from (1a). The interpretation of this effect is that we expect a 1-dollar increase in the current month's price of natural gas to increase the the price of oil in the current month by approximately `r round(ols_1i$coefficients[2], 3)`—holding all else constant.

Our estimate for $\beta_3$ is approximately `r round(ols_1i$coefficients[4], 3)`, which is also statistically significant at the 5-percent level. The interpretation of this effect is that we expect a 1-dollar increase in the previous month's price of oil to increase the the price of oil in the current month by approximately `r round(ols_1i$coefficients[4], 3)`—holding all else constant.

]

**1j.** Compare the R.super[2] from model $(1\text{i})$ to the R.super[2]s of the previous models. Explain what happened.

.pink[
.b[Answer] The R.super[2] in the current model (1i) is now approximately `r summary(ols_1i)$r.squared %>% round(4)`, which is **much** higher than the R.super[2] values we saw in the previous two models. It appears as though the price of oil is very strongly correlated with the previous month's price of oil: once we control for one lag of the price of natural, we are able to account for a *substantial* amount of the variation in the price of oil.
]

---
class: clear

**1k.** Plot the prices against time. Does it look like we should be concerned about nonstationarity? Explain.

.pink[

.b[Answer]

```{R, key 1k, out.width = '90%', fig.asp = 1/3, dev = 'svg', echo = T, include = T}
# Load 'ggplot2' and 'ggthemes' packages
p_load(ggplot2, ggthemes)
# Plot the price of oil over time
ggplot(data = price_df, aes(x = month_year, y = price_oil)) +
geom_line(size = 0.2) +
geom_point(size = 0.5) +
geom_hline(yintercept = 0) +
xlab("Date (months)") +
ylab("Price of oil (USD)") +
theme_pander()
# Plot the price of natural gas over time
ggplot(data = price_df, aes(x = month_year, y = price_gas)) +
geom_line(size = 0.2) +
geom_point(size = 0.5) +
geom_hline(yintercept = 0) +
xlab("Date (months)") +
ylab("Price of natural gas (USD)") +
theme_pander()
```

It looks like the price of oil may be nonstationary, as its mean, $\mathop{E}\left[ P^\text{Oil}_t\right]$ tends to increase with time.

There may also be a violation of variance stationarity. The variance appears to increase in the middle period of both time series.

]

---
class: clear

**1l.** If we assume $u_t$ in $(1\text{i})$ (**A**) follows our assumption of *contemporaneous exogeneity* and (**B**) is not autocorrelated, should we expect OLS to produce consistent estimates for the $\beta$s in this model? **Explain.**

.pink[
.b[Answer] Yes, OLS is consistent for models with lagged dependent variables as long as the disturbances follow our assumptions of contemporaneous exogeneity and no autocorrelation.
]


## Problem 2: Autocorrelation

**2a.** After starting to estimate these time-series models, you remember that autocorrelation affects OLS. For each of the three models above (1a, 1d, and 1i), explain how autocorrelation will affect OLS.

.pink[
**ANSWER** For models (1a) and (1d), autocorrelated disturbances will cause OLS to (1) be inefficient and (2) have biased standard errors, but OLS will still be unbiased and consistent for the coefficients in (1a) and (1d).

In models like (1i), autocorrelation causes a violation of our contemporaneous exogeneity assumption, which causes OLS to be biased and inconsistent for estimating the coefficients in the model.
]

**2b.** Add the residuals from your estimate of model $(1\text{i})$ to your dataset.

**Important:** Don't forget that you will need to tell .mono[R] that you have a missing observation (since we have a lag in our model).

```{R, hint 2b}
# Add residuals from our estimated model in 1i to dataset 'price_df'
price_df$e_1i <- c(NA, residuals(ols_1i))
```

Here, I'm adding a new column to the dataset `price_df` for the residuals from the model I saved as `ols_1i`. The first observation is missing, because our model `ols_1i` includes a single lag.


.pink[
.b[Answer] Done in hint.
]

---
class: clear

**2c.** Construct two plots with the residuals from $(1\text{i})$: .hi[1] plot the residuals against the time variable (`t_month`) and .hi[2] plot the residuals against their lag. Do you see any evidence of autocorrelation? What would autocorrelation look like?

I strongly encourage you to use `ggplot2` for these graphs.

.pink[

.b[Answer]

```{R, key 2c, out.width = '90%', fig.asp = 1/4, warning = F, message = F, dev = 'svg', include = T}
# Plot 1: Residuals over time
ggplot(data = price_df, aes(x = t_month, y = e_1i)) +
geom_path(size = 0.2) +
geom_point(size = 0.5) +
xlab("Time") + ylab("Residual (1i)") +
theme_pander()
# Plot 2: Residuals against their lags
ggplot(data = price_df, aes(x = lag(e_1i), y = e_1i)) +
geom_point(size = 0.5) +
geom_smooth(method = lm, se = F, alpha = 0.5) +
xlab("Lagged residual (1i)") + ylab("Residual (1i)") +
theme_pander()
```

This figures might suggest autocorrelation.

In the first figure, we're looking for residuals to closely follow the residual that preceded them—for example, larger residuals followed by other large residuals. This seems to be the case—especially in the middle and end of the the time series.

In the second figure, autocorrelation would look show up with residuals forming some sort of line. There *may* be a positive relationship between the current residual and its lag (the .b.blue[blue line]).

]

---
class: clear

**2d.** Add the residuals from the models in $(1\text{a})$ and $(1\text{d})$ to your dataset. See below (we have to keep track of missing observations due to lags).

```{R, hint 2d, include = T}
# Residuals from the model in 1a
price_df$e_1a <- residuals(ols_1a)
# Residuals from the model in 1d
price_df$e_1d <- c(NA, NA, residuals(ols_1d))
```

.pink[.b[Answer] Done in hint.]

**2e.** Repeat the plots from above—.hi[1] plot the residuals against the time variable (`t_month`) and .hi[2] plot the residuals against their lag—for both sets of residuals, *i.e.*, for the residuals from $(1\text{a})$ and for the residuals from $(1\text{d})$. You should end up with four graphs for this part.

.pink[

.b[Answer]

```{R, key 2e 1a, out.width = '90%', fig.asp = 1/4, warning = F, dev = 'svg', include = T}
# Plot 1a 1: Residuals over time
ggplot(data = price_df, aes(x = t_month, y = e_1a)) +
geom_path(size = 0.2) +
geom_point(size = 0.5) +
xlab("Time") + ylab("Residual (1a)") +
theme_pander()
# Plot 1a 2: Residuals against their lags
ggplot(data = price_df, aes(x = lag(e_1a), y = e_1a)) +
geom_point(size = 0.5) +
xlab("Lagged residual (1a)") + ylab("Residual (1a)") +
theme_pander()
```

]

---
class: clear

.pink[

.b[Answer, continued]

```{R, key 2e 1d, out.width = '90%', fig.asp = 1/4, warning = F, dev = 'svg', include = T}
# Plot 1d 1: Residuals over time
ggplot(data = price_df, aes(x = t_month, y = e_1d)) +
geom_path(size = 0.2) +
geom_point(size = 0.5) +
xlab("Time") + ylab("Residual (1d)") +
theme_pander()
# Plot 1d 2: Residuals against their lags
ggplot(data = price_df, aes(x = lag(e_1d), y = e_1d)) +
geom_point(size = 0.5) +
xlab("Lagged residual (1d)") + ylab("Residual (1d)") +
theme_pander()
```

]

**2f.** Why do you think the residuals from $(1\text{a})$ and $(1\text{d})$ appear to have autocorrelation, while the residuals in $(1\text{i})$ show much less evidence of autocorrelation?

*Hint:* Think back to our discussion of the ways we can work/live with autocorrelation.

.pink[
.b[Answer] Model misspecification can cause autocorrelation in the disturbance if an omitted variable is, itself, autocorrelated. In this case, if the current price of oil depends strongly on the previous period's price of oil, then if we fail to control/include the previous period's price of oil (as we do in (1a) and (1d)), then the previous period's price of oil shows up in the disturbance/residual, which is likely causing at least some of the autocorrelation.
]

---
class: clear

**2g.** Following the steps for the Breusch-Godfrey test that we discussed in class, test the residuals from the model in $(1\text{i})$ for second-order autocorrelation.

*Hint:* You can use the `waldtest()` from the `lmtest` package, as shown in the lecture slides.

.pink[

.b[Answer]

Because (1i) includes a lagged outcome variable, we use the **Breusch-Godfrey** test. We already completed the **first step** (estimating the model with OLS) and the **second step** (recording the residuals).

The **third step** involves regressing the residuals on the original explanatory variables and lags of the residuals (here: 2 lags).

```{R, key 2g, include = T}
# Regress residuals on explanatory variables and two lags of residuals
bg_2g <- lm(
  e_1i ~ price_gas + lag(price_gas, 1) + lag(price_oil, 1) + lag(e_1i, 1) + lag(e_1i, 2),
  data = price_df
)
# F test
waldtest(bg_2g, c("lag(e_1i, 1)", "lag(e_1i, 2)"))
```

The **fourth step** invovles an $F$ test for the two lags. The $F$ test above has a *p*-value of approximately `r waldtest(bg_2g, c("lag(e_1i, 1)", "lag(e_1i, 2)")) %>% tidy %>% magrittr::extract2(2,4) %>% format(scientific = F, digits = 3)`, which means we reject H.sub[o] at the 5-percent level.

In the **fifth step**, we make our conclusion. Here, H.sub[o] is "no autocorrelation". Thus, we reject "no autocorrelation"—meaning we find statistically significant evidence of autocorrelation for model (1i) at the 5-percent level.

]

**2h.** If we assume $u_t$ is **not** autocorrelated, then can we trust OLS to be consistent for its estimates of the coefficients in model $(1\text{i})$? **Explain.**

.pink[
.b[Answer] Because model (1i) has a lagged outcome variable, we can trust OLS to consistently estimate the coefficients in (1i) *if* there is not autocorrelation in the disturbances $u_t$ (and as long as there are no other violations of our assumptions).
]

**2i.** Should we interpret our estimates from $(1\text{i})$ as causal? **Explain.**

.pink[

.b[Answer] Probably not. It is not even clear which way the causal relationship would go—do natural gas prices influence oil prices, do oil prices influence natural gas prices, or do they both influence each other? There are definitely omitted variables—variables that affect the prices of both natural gas and oil. Plus we've found evidence of autocorrelation and we have a lagged dependent variable, so the estimate is potentially biased/inconsistent. (We also probably want to think about nonstationarity.)

]

---
class: clear

### Description of variables and names
<br>
```{R, background variables, echo = F, warning = F, message = F, error = F}
p_load(kable, kableExtra)
var_tbl <- data.frame(
  Variable = names(price_df) %>% magrittr::extract(1:7) %>% paste0(".mono-small[", ., "]"),
  Description = c(
    "The observation's month and year (.mono-small[character])",
    "The month (.mono-small[numeric])",
    "The year (.mono-small[numeric])",
    "The average (Henry Hub) price of natural gas, $ per 1MM BTU (.mono-small[numeric])",
    "The average (Brent Crude) price of oil, $ per barrel (.mono-small[numeric])",
    "Time, measured by months in the dataset (.mono-small[numeric])",
    "Time, approximately by fractions of years (.mono-small[numeric])"
  )
)
kable(var_tbl) %>%
  kable_styling(full_width = F)
```

```{R, generate pdfs, include = F, eval = T}
system("decktape remark ps03Solutions.html ps03Solutions.pdf --chrome-arg=--allow-file-access-from-files")
```
