---
title: "Problem Set 1"
subtitle: "Econometrics Review"
author: "**EC 421:** Introduction to Econometrics"
date: "<br>Due *before* midnight (11:59pm) on Sunday, 21 April 2019"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: clear

```{R, setup, include = F}
# Packages
library(pacman)
p_load(
  ggplot2, gridExtra, ggthemes, latex2exp, kableExtra,
  tidyverse, broom, knitr, magrittr
)
# Colors
red_pink <- "#e64173"
turquoise <- "#20B2AA"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
# Themes
theme_axes_y <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.y = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_x <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.x = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_set(theme_gray(base_size = 11))
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  warning = F,
  message = F
)
```

.mono[**DUE**] Your solutions to this problem set are due *before* 11:59pm on Sunday, 21 April 2019 on [Canvas](https://canvas.uoregon.edu/). .hi[Your answers must include two files] (.hi[1]) your responses/answers to the question (_e.g._, a Word document) and (.hi[2]) the .mono[R] script you used to generate any answers in .mono[R]. Each student must turn in her/his own answers.

.mono[**OBJECTIVE**] This problem set has three purposes: (1) reinforce the econometrics topics we reviewed in class; (2) build your .mono[R] toolset; (3) start building your intuition about causality within econometrics.

## Problem 1: Bias and variance

**1a.** Throughout this course, we will use the OLS estimator $\hat{\beta}$ to estimate $\beta$. Explain what it means for $\hat{\beta}$ to be biased for $\beta$.

**Figure 1**
```{R, fig1, echo = F, dev = "svg", fig.height = 3.5}
# Three distributions
ggplot(data = tibble(x = c(-5, 45)), aes(x)) +
stat_function(
  fun = dchisq, args = list(df = 2.5), n = 1e4,
  geom = "area", fill = "grey10", color = "black", alpha = 0.4, size = 0.3
) +
stat_function(
  fun = dnorm, args = list(mean = 20, sd = 3), n = 5e3,
  geom = "area", fill = "grey50", color = "black", alpha = 0.3, size = 0.3
) +
stat_function(
  fun = dnorm, args = list(mean = 20, sd = 7), n = 5e3,
  geom = "area", fill = "grey70", color = "black", alpha = 0.3, size = 0.3
) +
geom_vline(xintercept = 20, linetype = "dotted", alpha = 0.5) +
annotate(geom = "text", x = 20, y = -0.015, label = TeX("$\\beta$"), hjust = 0.5, size = 5) +
annotate(geom = "text", x = 2.75, y = 0.2, label = "A") +
annotate(geom = "text", x = 16.8, y = 0.1, label = "B") +
annotate(geom = "text", x = 32, y = 0.02, label = "C") +
theme_void()
```
**Note** This figure shows the distributions of three estimators (A, B, and C) that each estimate the unknown parameter $\beta$. E[A]= $\beta-3$, E[B]= $\beta$, E[C]= $\beta$

**1b.** Which of the estimators in Figure 1 (above) are unbiased? *Hint:* There may be more than one.

**1c.** Which of the estimators in Figure 1 (above) has the minimum variance?

**1d.** Which of the estimators in Figure 1 (above) is the best (minimum variance) unbiased estimator?

**1e.** Suppose we want to estimate the effect of advertising on sales. Explain what it *bias* would mean in this context.

**1f.** What does the term "standard error" mean?

---
class: clear

## Problem 2: Getting started

Now we will start exploring data in .mono[R].

.mono[**README**!] The data<sup>†</sup> in the next two sections of this problem set come from the paper ["Are Emily and George More Employable than Lakisha and Jamal? A Field Experiment on Labor Market Discrimination"](https://www.aeaweb.org/articles?id=10.1257/0002828042002561) by Bertrand and Mullainathan (published in the *American Economic Review* (AER) in 2004).<sup>††</sup> In their (very influential) paper, Bertrand and Mullainathan use a clever experiment to study the effects of race in labor-market decisions by sending fake résumés to job listings. To isolate the effect of race on employment decisions, Bertrand and Mullainathan randomize whether the résumé lists a typically African-American name or a typically White name.

**2a.** Open up RStudio, start a .mono[R] new script (File ➡ New file ➡ R Script). You will hand in this script as part of your assignment.

**2b.** Load the the `pacman` package. If you haven't installed it, you will need first install it (`install.packages("pacman")`) *and then* load it (`library(pacman)`).

Now use `pacman`'s function `p_load` to load the `tidyverse` package, _i.e._,

```{R, example pload, eval = F}
# Load the 'pacman' package
library(pacman)
# Load the packages 'tidyverse' and 'haven'
p_load(tidyverse)
```

*Note:* If `tidyverse` is not already installed, then `p_load(tidyverse)` will automatically install it for you—this is why we're using `pacman`.

**2c.** [Download](https://raw.githack.com/edrubin/EC421S19/master/Data/ps01_data.csv) the dataset ([Canvas link](https://canvas.uoregon.edu/)). Save it in a helpful location. Remember this location.

**2d.** Read the data into .mono[R]. What are the dimensions of the dataset (numbers of rows and columns)?

*Hints:* The `read_csv()` function reads CSVs into .mono[R], _e.g._, `read_csv("file.csv")`. The `dim()` function will tell you the dimensions of a dataset, _e.g._, `dim(some_data)`.

```{R, key 2d, include = F}
# Read in the data
ps1_df <- read_csv("ps01_data.csv")
# Dimensions of the dataset:
# 1. Printed to screen (since it's a tibble)
ps1_df
# 2. Use dim()
dim(ps1_df)
```

*Note:* Let each row in this dataset represent a different résumé sent to a job posting. The table on the last page explains each of the variables.

**2e.** What are the names of the first five variables? *Hint:* `names(your_df)`

```{R, key 2e, include = F}
names(ps1_df) %>% head(5)
```

**2f.** What are the first two *first names* in the dataset (`first_name` variable)?

*Hint:* `head(your_df$var_name, 10)` gives the first 10 observations of the variable `var_name` in dataset `your_df`.

```{R, key 2f, include = F}
head(ps1_df$first_name, 2)
```

.footnote[
[†]: The data that we use in the problem set contain a subset of the variables from the original paper.

[††]: [Here's a link](https://medium.com/@brooke.cusmano/are-emily-and-greg-more-employable-than-lakisha-and-jamal-13d11dfac511) to an article on Medium that discussed their paper.
]
---
class: clear

## Problem 3: Analysis

Reviewing the basic analysis tools of econometrics.

**Note:** When you use OLS to regress a binary indicator variable (like `i_callback`) on a set of explanatory variables, your coefficients are telling you how the explanatory variables affect the probability that the indicatory variable equals one. So if we regress `i_callback` on `n_jobs`, the coefficient on `n_jobs` tells us how the probability of a callback changes with each additional job listed on the résumé.

**3a.** What percentage of the résumés generated a callback (`i_callback`)?

*Hint:* The mean of a binary indicator variable (_i.e._, `mean(binary_variable)`) gives the percentage of times the variable equals one. *E.g.*, `mean(call_df$female)` would give us the percentage of female individuals in our dataset `call_df`.

```{R, key 3a, include = F}
mean(ps1_df$i_callback)
```

**3b.** Calculate percentage of callbacks (_i.e._, the mean of `i_callback`) for each racial group (`race`). Does it appear as though employers considered an applicant's race when making callbacks? Explain.

*Hint:* `filter(your_df, race == "b")` will select all observations (from the dataset `your_df`) where the variable `race` takes the value `"b"`. Similarly `filter(your_df, race == "b")$i_callback` will give you the values of `i_callback` for obsevations whose value of `race` is `"b"`.

```{R, key 3b, include = F}
# Percentage for Black
filter(ps1_df, race == "b")$i_callback %>% mean()
# Percentage for White
filter(ps1_df, race == "w")$i_callback %>% mean()
```

**3c.** What is the difference in the groups' mean callback rate?

```{R, key 3c, include = F}
# Percentage for Black
mean_b <- filter(ps1_df, race == "b")$i_callback %>% mean()
# Percentage for White
mean_w <- filter(ps1_df, race == "w")$i_callback %>% mean()
# Difference:
mean_b - mean_w
```

**3d.** Based upon the difference in percentages that we observe in **3b.**, can we conclude that employers consider race in hiring decisions? **Explain your answer.**

<!-- **No.** We have shown a difference in the groups' percentages, but we do not know if this difference is statistically meaningful. -->

**3e.** Without running a regression, conduct a statistical test for the difference in the two groups' average callback rates (_i.e._, test that the proportion of callbacks is equal for the two groups).

*Hint:* Back to your statistics class—difference in proportions (a *Z* test) or means (a *t* test).

```{R, key 3e, include = F}
# Percentage for everyone
mean_all <- ps1_df$i_callback %>% mean()
# Number: Black
n_b <- filter(ps1_df, race == "b") %>% nrow()
# Number: White
n_w <- filter(ps1_df, race == "w") %>% nrow()
# The Z statistic
z_stat <- (mean_b - mean_w) / sqrt(mean_all * (1 - mean_all) * (1/n_b + 1/n_w))
# The p value
2 * pnorm(abs(z_stat), lower.tail = F)
```

**3f.** Now regress `i_callback` (whether the résumé generated a callback) on `i_black` (whether the résumé's name implied a black applicant). Report the coefficient on `i_black`. Does it match the difference that you found in **3c**?

*Hint:* Use `lm(y ~ x, data = our_df)` to regress `y` on `x` from datatset `our_df`.

```{R, key 3f, include = F}
lm(i_callback ~ i_black, data = ps1_df) %>% summary()
```

**3g.** Conduct a $t$ test for the coefficient on `i_black` in the regression above in **3f**. Write our your hypotheses (both H.sub[0] and H.sub[A]), the test statistic, the *p*-value, the result of your test (_i.e._, reject or fail to reject H.sub[0]), and your conclusion.


**3h.** Now regress `i_callback` (whether the résumé generated a callback) on `i_black`, `n_expr` (years of experience), and the interaction between `i_black` and `n_expr`. Interpret the estimates for the coefficients (both the meaning of the coefficients and whether they are statistically significant).

*Hint:* In .mono[R], `lm(y ~ x1 + x2 + x1:x2, data = your_df)` regresses `y` on `x1`, `x2`, and the interaction between `x1` and `x2` (all from the dataset `your_df`).

```{R, key 3h, include = F}
lm(i_callback ~ i_black + n_expr + i_black:n_expr, data = ps1_df) %>% summary()
```

---
class: clear

## Problem 4: Thinking about causality

Now for the big picture.

This project by Bertrand and Mullainathan took a decent amount of time and effort—finding job listings, generating fake résumés, responding to the listings, *etc.* It would have been much quicker/cheaper/easier to just go out and get data from job applicants—whether they received callbacks and their races. So why didn't they take the easier, cheaper, and quicker route?

**4a.** Define omitted-variable bias.

**4b.** The central questions here is "Do employers call back individuals at different rates based upon their race (or gender)?".

If we collected data on callbacks and race, and we then regressed *Callback* on *Race*, we would likely get biased estimates due to omitted-variable bias.

Explain why this is the case and provide an example of an omitted variable in this situation.

**4c.** The point of experiments is to avoid omitted-variable bias. Explain how randomizing race on these (fake) résumés avoided the concerns for omitted-variable bias.

---
class: clear

### Description of variables and names
<br>
```{R, background variables, echo = F}
var_tbl <- data.frame(
  Variable = names(ps1_df) %>% paste0(".mono-small[", ., "]"),
  Description = c(
    "Binary variable (0,1) for whether the resume received a callback.",
    "Number of previous jobs listed on the application.",
    "Number of years of experience listed on the application.",
    "Binary variable for whether the application included military status.",
    "Binary variable for whether the application included computer skills.",
    "The first name listed on the application.",
    "The implied sex of the first name on the application (.mono-small['f'] or .mono-small['m']).",
    "Binary indicator for whether the implied sex was female.",
    "Binary indicator for whether the implied sex was male.",
    "The implied race of the first name on the application (.mono-small['b'] or .mono-small['w']).",
    "Binary indicator for whether the implied race was African American.",
    "Binary indicator for whether the implied race was White."
  )
)
kable(var_tbl) %>%
  kable_styling(full_width = F)
```

In general, I've tried to stick with a naming convention. Variables that begin with .mono-small[i\\_] denote binary indicatory variables (taking on the value of .mono-small[0] or .mono-small[1]). Variables that begin with .mono-small[n_] are numeric variables.

```{R, generate pdfs, include = F, eval = T}
system("decktape remark ps01.html ps01.pdf --chrome-arg=--allow-file-access-from-files")
```
